# Generated by Django 5.2.17 on 2026-09-13 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citation", "0035_alter_auditcommand_id_alter_auditlog_id_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestedmerge",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("app_label", "citation"),
                    (
                        "model__in",
                        ["author", "container", "platform", "sponsor", "tag"],
                    ),
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suggested_merge_set",
                to="contenttypes.contenttype",
            ),
        ),
    ]
